# Book, Series, Universe, Cateogry, Youtube ID, title
episode_data = [("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "eQbNUOrKdSE", "Oathbringer Part Two Epigraphs - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "iDKOfoq6ky0",
                 "Oathbringer Reactions! - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "eDwDfeodpf8",
                 "Oathbringer Part Three Epigraphs - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Live Event", "JJiErDnwJoc",
                 "OJ Goes To London's Oathbringer Signing!"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "IxAaBuieoKk",
                 "The Unmade And Oathbringer Part Four Epigraphs - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "_Sm0MYZzC6A",
                 "The Stormlight Love Triangle - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "w1nzHmQCM7k",
                 "State of the Sanderson 2017 - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Solo Review", "0aFDKxQJmcQ",
                 "Jebus's Oathbringer First Impressions"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast",
                 "_KYsb98Kwng", "The Recreance - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "Dak99Htf7S4",
                 "The Visit to the Valley - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast",
                 "i7zvmhwt9EU", "Moash - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "stDAyfBbNIA",
                 "Oathbringer Tour Words of Brandon Part 1: Letter Confirmations! - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "f48SNFajKIw",
                 "Oathbringer Tour Words of Brandon Part 2 - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "8N3hTx_HfvI",
                 "Oathbringer Tour Words of Brandon Part 3 - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Outtakes",
                 "VsvJ0gPSLno", "Outtakes - Shardcast"),
                ("White Sand", "White Sand", "Cosmere", "Shardcast", "L59oE3-IMTA",
                 "White Sand Vol. 1 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Interview", "Rt0XZb6rCnU",
                 "An Interview with Arcturus XR - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "6I3bXgAGf1k",
                 "Sja-anat and Voidbinding - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "bWwjDVQ5uEs",
                 "Savantism, Resonances, and Compounding - Shardcast"),
                ("Multipe", "Multiple", "Cosmere", "Shardcast", "OT3m64Xuako",
                 "Patji, VR Experience, ECCC Words of Brandon - Shardcast"),
                ("Multipe", "Multiple", "Cosmere", "Shardcast", "R-u4Lp-HfgA",
                 "Emerald City Comic Con Words of Brandon - Shardcast"),
                ("White Sand", "White Sand", "Cosmere", "Shardcast", "lnrlp3OFW2w",
                 "White Sand Vol. 2 (Featuring Trell?) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "_RUiWsLWmPI",
                 "Secret Societies of Roshar - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "CPlJtXFw5l4",
                 "Venli and Eshonai - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "yOKB_H3Sndo",
                 "Nightblood 2: Electric Boogaloo - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "tOpmBWrEF9w",
                 "The Sibling and Urithiru - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "z3DLOAPzI04",
                 "JordanCon and The Traveler - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "-hPoE9bpqKY",
                 "JordanCon Words of Brandon Analysis - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "E7oHjSFh954",
                 "JordanCon Words of Brandon Part 2 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "eg_Dx706_EU",
                 "Aimia and Akinah - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "zsQqnVghDSY", "Odium - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "9k-JuxX2fRs", "Odium v Passion - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "oeS1hh_CCKQ", "The Singers - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "wGnhZr3NXVo",
                 "New Shard? MisCon and BookCon Words of Brandon - Shardcast"),
                ("Dark One", "Dark One", "Dark One", "Bonuscast",
                 "BxuV4Ehoy08", "Bonuscast: Dark One News"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast",
                 "0XNiI33qpns", "Unity - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "HQkj1fNaxZY", "The Oathpact - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "qpfwaRZRfbU", "The Heralds - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast",
                 "noEmwqgqGWs", "Cosmere Beefs - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "WFg1OC85Keo",
                 "Fabrials and Soulcasters - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "Fm1pjjVAV_k", "Half-Shards - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "-27UfUzeDxE",
                 "The Missing Shardblades - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "EaEFLmAhoTk",
                 "Adonalsium's Opposition and Idaho Falls Words of Brandon - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "2-BVn0OS7Mg",
                 "Vax and Weird Things - Shardcast"),
                ("Warbreaker", "Warbreaker", "Cosmere", "Shardcast",
                 "_-WsbS0vmb4", "Endowment - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "D8Vf09iSlSo",
                 "Keeping Up With The Kholins (Gavilar and Navani) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "jnXrZNoBG4o",
                 "Keeping Up With The Kholins (Elhokar, Aesudan, and Jasnah) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Special", "03Om1jQ46kQ",
                 "Creating Stormlight Glyphs - JordanCon 2018"),
                ("Legion", "Legion", "Legion", "Shardcast", "h4qlTREzl_g",
                 "Legion Reactions - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "R9cLe1wC0-8",
                 "Cultivationlight!? FanX Words of Brandon P1 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "OOisXTW7TyY",
                 "Prologue Character Confirmations! FanX Words of Brandon Part 2 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "iXdjXNLi41E",
                 "Keeping Up With The Kholins (Dalinar, Evi, and Navani) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "36hwkIIgsLE",
                 "Keeping Up With The Kholins (Adolin and Renarin) - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "qOnK55chRWA",
                 "Nightblood Confirmations! Legion Release Words of Brandon P1 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "8-qKR4CRW8s",
                 "Stormstriders? Legion Release WoBs Part 2 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "O14KIExToAc",
                 "Frost and Dragons - Shardcast"),
                ("Skyward", "Skyward", "Cytoverse", "Shardcast", "cZqnI91lsZ8",
                 "Skyward Reactions (ON VIDEO!) - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "4AZHHBIKxUE",
                 "Cosmere Pronunciation - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast",
                 "wrn8Bhf8vtI", "Cosmere Crushes - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "p57H1jcWqJM",
                 "Dealing With The Davars - Shardcast"),
                ("Starsight", "Skyward", "Cytoverse", "Shardcast", "R21D9bMiWtQ",
                 "Starsight Predictions and Skyward Lore - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "ilkAm7Pv_PM",
                 "Skyward Tour Words of Brandon #1 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "PBZgSUuKJlw",
                 "State of Sanderson 2018 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "y9AH4LM_vAA",
                 "Hoid Wouldn't Hold Nightblood - Skyward Tour Words of Brandon #2 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "FxyKEGLsLZY",
                 "Heralds and Ashyn!? - Skyward Tour Words of Brandon #3 - Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "hLM7hql2zFo",
                 "The Hemalurgy Table! (Part 1) - Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "7g8nI-DnZ5g",
                 "Hemalurgy, Bind Points, and More! (Hemalurgy Table Part 2) - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "AOIrTEJ3VGY",
                 "Cognitive Mumbo Jumbo - Skyward Tour #4 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "Ka1xz0gPeoA",
                 "\"Who Needs Rails?\" - Idaho Falls Holiday Words of Brandon - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "5Y8w0snoQOw",
                 "History of Roshar Part 1 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "1at78WNWhY8",
                 "History of Roshar Part 2 - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "dT9xez4BWpA",
                 "Cognitive Shadows - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere",
                 "Shardcast", "YSHTdoQeBXU", "Shardplatecast!"),
                ("Children of the Nameless", "Children of the Nameless", "Magic the Gathering", "Shardcast", "6el9YiphTH4",
                 "Children of the Nameless - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "qYQZnId8Xxo",
                 "Death Rattles Analysis #1 - Shardcast"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Shardcast", "RLsa6wexLTE",
                 "Oathbringer Retrospective - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "g36ltTGk9NE", "Death Rattles 2 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "QlT-My2NLD4",
                 "The Knights Radiant #1 (Windrunners, Skybreakers, Dustbringers) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "ZQSht-tQv1o",
                 "The Knights Radiant #2 (Edgedancers, Truthwatchers, and Lightweavers) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "XUo7TJGxGzI",
                 "The Knights Radiant #3 (Elsecallers, Willshapers, Stonewards, Bondsmiths) - Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "U4cZErprdYo",
                 "The Lord Ruler (Character and History) - Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "R2SFUvFGoU4",
                 "The Lord Ruler (Mechanics and Powers) - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "VnjbAuiqMOk",
                 "Who's That Cosmere Character? - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "RAoA3wdjDyo",
                 "March/April Words of Brandon and JordanCon Recap - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "5kV3RBrJs1k",
                 "Listener Songs #1 (Songs of Listing and Revision) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "NNn1piPdYg0",
                 "Listener Songs #2 (Songs of Histories, Wars, Winds, Secrets, and Spren) - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "Zz40zJLAIFU",
                 "Language and Connection - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "mbSzzM1_upQ",
                 "Spiritual Properties (Connection, Identity, Fortune) - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "NAaI5VkoDK8",
                 "Tropes Brandon Overuses - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "54aT9350L1s",
                 "Stormlight 4 Reading and Germany Words of Brandon - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "UVCRKOQOlL8",
                 "Ship It or Rip It? - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "2vbXoOvfPFg",
                 "Cultivation and Her Plans (Plus Another SA4 Reading) - Shardcast"),
                ("Warbreaker", "Warbreaker", "Cosmere", "Shardcast", "jD69it4YY6k",
                 "The Five Scholars - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "y5Nhkm2iCuY",
                 "The Girl Who Looked Up (Myths of Roshar #1) - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "xq_h3bD7kbQ",
                 "Myths of Roshar #2 - Shardcast"),
                ("", "", "", "Announcement", "9LNFRtHSvWg",
                 "Shardcast is now going to be every other week"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "MpAcNSKH7xw", "Iri and Kurth - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "qqIVBzltcjE",
                 "Stormlight 4 Prologue Reading and Update - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "NJYqAjHq9Cc",
                 "DragonCon Words of Brandon - Shardcast"),
                ("White Sand", "White Sand", "Cosmere", "Shardcast", "ZFyh_w-Q5UM",
                 "White Sand Vol 3 - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "ZWFvcmNR1BE",
                 "Who's That Cosmere Character #2 - Shardcast"),
                ("White Sand", "White Sand", "Cosmere", "Shardcast",
                 "ERdAg1_dWuI", "Autonomy - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "dhxz_g3Weqw",
                 "Nalthis Star Chart, More Stormlight 4 Prologue, and Tons of WoBs!"),
                ("Starsight", "Skyward", "Cytoverse", "Shardcast", "N0wrSGZ0G_Y",
                 "Starsight Reactions - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "wGF8qRee_9I",
                 "State of the Sanderson 2019 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "39iXR_0BCso", "The Horneaters - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "hmCEffHy4HQ",
                 "Starsight Release WoBs 1: Into the Weeds - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "av9m9R57EgQ",
                 "Starsight Release WoBs 2 ft. Destiny Tangent - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "I9NZVzPRRTI",
                 "Spren and Spren Societies - Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "sU0PJKFMGLI",
                 "Rhythm of War (Stormlight 4) Predictions! - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast",
                 "OCL-QCGbgoU", "Shinovar - Shardcast"),
                ("Elantris", "Elantris", "Cosmere", "Shardcast", "GYtkuVXZC_I",
                 "History and Cultures of Sel - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "qGyuXOlYfxU",
                 "Ship it or Rip It 2 - Shardcast"),
                ("Warbreaker", "Warbreaker", "Cosmere", "Shardcast", "mLq2EbtrOLc",
                 "Awakening and Breath - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "PHJXOSAmKPE",
                 "Making Fun of Our Old Cosmere Theories - Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "VzHzCA9DVh0",
                 "Dead Loved Ones in the Cosmere - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "Mx0AZrdhLFg",
                 "Tenth Anniversary Livestream! Part 1 - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "Bi9_z2OQYnM",
                 "Tenth Anniversary Livestream! Part 2 - Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "5K6l84Y-ZdA",
                 "Knights Radiant Quiz with New Lore! - Shardcast"),
                ("Dark One", "Dark One", "Dark One", "Shardcast", "kd320aE9umU",
                 "Dark One Reactions and Analysis - Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Overlady Reads", "j6Kt7mt6nuQ",
                 "The Overlady Reads Mistborn Era 1!"),
                ("Multiple", "Mistborn", "Cosmere", "Overlady Reads", "z4q-GOfSyc4",
                 "The Overlady Reads Mistborn Era 2 & Secret History!"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "SibxJN_woWA",
                 "New Rhythm of War Chapter! - Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Interview", "GnKvvrUsMT0",
                 "Interview with Isaac and Kara Stewart"),
                ("Elantris", "Elantris", "Cosmere", "Overlady Reads", "43SihUJaZ-g",
                 "The Overlady Reads Elantris!"),
                ("Dawnshard", "Stormlight Archive", "Cosmere", "Shardcast", "EjVsMk6zUzo",
                 "Dawnshard Novella Title & Predictions? - Not Bonuscast"),
                ("Warbreaker", "Warbreaker", "Cosmere", "Overlady Reads", "pkLaemA-VIc",
                 "The Overlady Reads Warbreaker!"),
                ("Multiple", "Multiple", "Cosmere", "Live Stream",
                 "FT4YIJIV2B8", "5000 Subscriber Q&A!"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "u1MWHyj8gr8",
                 "Rhythm of War Prologue through Ch 3 | Rhythm of Previews"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "GeYKgefkujw",
                 "Rhythm of War Chapters 4 and 5 | Rhythm of Previews"),
                ("Way of Kings", "Stormlight Archive", "Cosmere", "Overlady Reads", "wUnA3TAsd1E",
                 "The Way of Kings, Parts 1&2 | The Overlady Reads the Cosmere"),
                ("Dark One", "Dark One", "Dark One", "Shardcast",
                 "hXxdF2r6Aq8", "Dark One Lore | Shardcast"),
                ("Way of Kings", "Stormlight Archive", "Cosmere", "Overlady Reads", "H5d58zGo730",
                 "The Way of Kings Parts 3-5 | The Overlady Reads the Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "4jwWUO292b0",
                 "Rhythm of War Ch 6 | Rhythm of Previews"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "I_LdOIvcqlQ",
                 "Rhythm of War Ch 7 |  Rhythm of Previews"),
                ("Words of Radiance", "Stormlight Archive", "Cosmere", "Overlady Reads", "wzk7gKiQPgc",
                 "Words of Radiance Parts 1&2 | The Overlady Reads the Cosmere"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "ELln_Ydn9Ao",
                 "Dawnshard Prologue & 2020 Words of Brandon Part 1 | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "eSYaKUBdpnY",
                 "Rhythm of War Ch 8 | Rhythm of Previews"),
                ("Words of Radiance", "Stormlight Archive", "Cosmere", "Overlady Reads", "J0jPRYL_46Q",
                 "Words of Radiance Part 3 | The Overlady Reads the Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "hBBGbQPhC8Y",
                 "Rhythm of War Ch 9 | Rhythm of Previews"),
                ("Words of Radiance", "Stormlight Archive", "Cosmere", "Overlady Reads", "mywaXe29U3k",
                 "Words of Radiance Parts 4-5 | The Overlady Reads the Cosmere"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "SYiTswL8Ulo",
                 "2020 Words of Brandon Part 2 | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "iSOppNUW30I",
                 "Rhythm of War Ch 10 | Rhythm of Previews"),
                ("Edgedancer", "Stormlight Archive", "Cosmere", "Overlady Reads", "aj_Oezr25Fc",
                 "Edgedancer | The Overlady Reads the Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "48XqBxnyKUs",
                 "Rhythm of War Ch 11 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "dbjqoukLtMk",
                 "Oathbringer Recap, Part One | The Overlady Reads The Cosmere"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "wb5o7gE3aws",
                 "Who's That Cosmere Character 3, Off the Rails Edition | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "8PzQ-w_mRM0",
                 "Rhythm of War Ch 12 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "rCnQGvTDlc4",
                 "Oathbringer Recap, Part Two | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "FhztWg2UTUs",
                 "Rhythm of War Ch 13 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "sNJurCMUkFo",
                 "Oathbringer Recap, Part Three | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "Kr7yOd_ARGk",
                 "Rhythm of War Ch 14 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "kCl4ofx93To",
                 "Oathbringer Recap, Part Four | The Overlady Reads The Cosmere"),
                ("The Original", "The Original", "The Original", "Shardcast", "ObR9Pc0MUYw",
                 "The Original Reactions | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "VoKQLXAFs4E",
                 "Rhythm of War Ch 15 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "GwkLObhuFRM",
                 "Oathbringer Recap, Part Five | The Overlady Reads the Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "08IyvmYgAAw",
                 "Rhythm of War Ch 16 | Rhythm of Previews"),
                ("Oathbringer", "Stormlight Archive", "Cosmere", "Overlady Reads", "YAxDviCuVfw",
                 "Oathbringer Reactions/Rhythm of War Theories | The Overlady Reads The Cosmere"),
                ("Warbreaker", "Warbreaker", "Cosmere", "Shardcast",
                 "NDlOSVGKGg4", "The Returned | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "zUgd1XGQ_qs",
                 "Rhythm of War Ch 17 | Rhythm of Previews"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Overlady Reads", "PjP6VFD19qc",
                 "The Overlady & Overlord take the Knights Radiant Quiz, With a TWIST!!"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Announcement", "ffYH1SMJWJ8",
                 "Roshar Interactive Map & Timeline Announcement Trailer"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "B5j41YJ82Ls",
                 "Rhythm of War Ch 18 | Rhythm of Previews"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Solo Review", "VOEEfkKhQow",
                 "Rhythm of War Review (Spoiler Free!)"),
                ("Arcanum Unbounded", "Multiple", "Cosmere", "Overlady Reads", "kTnV7HeodLo",
                 "Arcanum Unbounded | The Overlady Reads The Cosmere"),
                ("Dawnshard", "Stormlight Archive", "Cosmere", "Shardcast", "VOkx-LkipHU",
                 "Dawnshard Reactions | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "zI7Vv7v_L2M",
                 "Rhythm of Previews Ch 19 (End of Preview Chapters!) | Rhythm of Previews"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Overlady Reads", "t_pQ5RKFaYA",
                 "Rhythm of War Reaction, Part One | The Overlady Reads The Cosmere"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast",
                 "6JakItmPf54", "The Dawnshards | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "EHfS4ceap94",
                 "Rhythm of War Part Two Epigraphs (Part Two Spoilers Only) | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Solo Review", "nrxULp9p_QE",
                 "10 Crazy Things in Rhythm of War! (MASSIVE FULL BOOK SPOILERS)"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Overlady Reads", "OnR_GDLxUEI",
                 "Rhythm of War Reaction, Part Two | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "nqGr0G57oyk",
                 "Rhythm of War Reactions 1 (FULL BOOK SPOILERS) | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "QBUV5_E7Bto",
                 "Rhythm of War Reactions and Discussion 2 | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Overlady Reads", "g9DQ7BYVi9c",
                 "Rhythm of War Reaction, Part Three | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Overlady Reads", "HvGYh85EYlw",
                 "Rhythm of War Reaction, Part Four | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "lKJrNWaIDAU",
                 "Taravangian | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "6URHibtjSAk",
                 "Chatting with Daniel Greene about Fantasy, Cosmere, and Rhythm of War | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Overlady Reads", "LEksUtUUb1E",
                 "Rhythm of War Reaction, Part Five | The Overlady Reads The Cosmere"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "OZM3y_tmMwk",
                 "Lights | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "S-QI6O3B4-4",
                 "Rhythm of War Overall Thoughts | Rhythm of Reviews"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "8NT6DVKr_W8",
                 "State of the Sanderson 2020 | Shardcast"),
                ("Dawnshard", "Stormlight Archive", "Cosmere", "Overlady Reads", "c7TzlVhMPHs",
                 "Dawnshard | The Overlady Reads The Cosmere"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "Jj6kq4Ouv8E",
                 "Adolin and Shallan in Rhythm of War | Rhythm of Reviews"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "GoDBk1XxN8g",
                 "Ba-Ado-Mishram and the Recreance | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "-Sp-Obb5tBs",
                 "Kaladin and Navani in Rhythm of War | Rhythm of Reviews"),
                ("Sixth of the Dusk", "Sixth of the Dusk", "Cosmere", "Shardcast", "kM0sfy7IzXU",
                 "Sixth of the Dusk 2 Reading | Rhythm of War Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream",
                 "P9omcv6UuFs", "Chill New Years Stream"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "fn-PLsjS_YI",
                 "Venli and Flashbacks in Rhythm of War | Rhythm of Reviews"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "paAT4p2TyP0",
                 "Late 2020 & Rhythm of War Words of Brandon 1 | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Feleocast", "Sy3jlH-Xj4c",
                 "Dalinar, Jasnah, & Taravangian in Rhythm of War | Rhythm of Reviews"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "G-0uhCBH5so",
                 "Rhythm of War and Dawnshard Words of Brandon 2 | Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Interview", "fZMuK8i0Wwg",
                 "Shardcast ft. Brandon Sanderson [Rhythm of War and Cosmere Spoilers]"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Overlady Reads", "3q2HMwAxchE",
                 "How to Play: Call to Adventure Stormlight Archive edition"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "dTooA4YrjsA",
                 "Lord of Scars | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "CzndDJndXjA",
                 "Surges and Surgebinding | Rhythm of War Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Overlady Reads", "1_bzfLaiBW8",
                 "Let's Play: Call to Adventure, the Stormlight Archive Edition!"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "qQaq9PWj4v8",
                 "Renarin, Sja-anat, and Enlightened Truthwatchers | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "EkxiJfrkUxU",
                 "Renarin and Rlain | Rhythm of War Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream",
                 "2pCihXCnCJY", "Chill February Stream"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "96lCEbKyiSA",
                 "Fabrials and RoW Part One Epigraphs | Rhythm of War Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Overlady Reads",
                 "zP5Cmq_kgaA", "Making the Wines of Roshar!"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "6k19Mz12CsE",
                 "Fabrials in Rhythm of War and Dawnshard | Rhythm of War Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream", "c_YSMcN1VCU",
                 "17th Shard March Chatting Stream"),
                ("Cytonic", "Skyward", "Cytoverse", "Shardcast", "Zde3LJsE47M",
                 "Cytonic (Skyward 3) Predictions | Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "NFpvT4lfRu8",
                 "Rhythm of War Who's That Cosmere Character | Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream", "QbOJwKOaMIo",
                 "17th Shard April Chatting Stream"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "ARngZNp1noo",
                 "Q1 2021 Words of Brandon: Our Brandon Interview and More! | Rhythm of War Shardcast"),
                ("Rhythm of War", "Stormlight Archive", "Cosmere", "Shardcast", "uuIXeOD61g0",
                 "Moash | Rhythm of War Shardcast"),
                ("Elantris", "Elantris", "Cosmere", "Overlady Reads", "qJvAR4ecojs",
                 "Who is the Mad Prince? (Elantris)"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "arPAYKmnUqA",
                 "He Who Quiets | Rhythm of War Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream", "ubHsYBZTH18",
                 "17th Shard June Chatting Stream: 17S Turns 11!"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "IgU9-dWXw4k",
                 "Ishar | Rhythm of War Shardcast"),
                ("Way of Kings", "Stormlight Archive", "Cosmere", "Unboxing", "PG7WDAKGu6Q",
                 "Unboxing Way of Kings Leatherbound Tier 6 Swag Pack + Dragon Wood Shop Coin Display!"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "a7W8SpsZ0OI",
                 "Queerness in the Cosmere | Rhythm of War Shardcast"),
                ("Words of Radiance", "Stormlight Archive", "Cosmere", "Overlady Reads", "aevz9Vh-ylA",
                 "What happened to Jasnah? (Words of Radiance)"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "EudC6a3Stvo",
                 "Blowing Up Sel's Cognitive Realm, Avatars, & More! | Q2 2021 Words of Brandon Part 1 | Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Challenge", "tGMtK_MfKAk",
                 "Cite the Sanderson Challenge!!"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "OpSAuDmuf4s",
                 "TenSoon was going to be WHAT? | Q2 2021 Words of Brandon Part 2 | Rhythm of War Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "YolU3Ks8e5M",
                 "Shallan's Past | Rhythm of War Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Event", "a-z5MrE__V4",
                 "I flew all the way to Atlanta, and all I (lovingly) got was some JORDANCON footage"),
                ("Multiple", "Multiple", "Multiple", "Outtakes",
                 "NZl1ug1g8Js", "JordanCon 2021 Outtakes"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "DezFoNxLLIg",
                 "Talking Mistborn Era 2 with Merphy Napier | Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream", "9r6CQEEND1k",
                 "17th Shard August Chatting Stream"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "15NP3rUEJKs",
                 "Lost Metal Reading & Taln Didn't Break?? | JordanCon 2021 WoBs Part 1 | Rhythm of War Shardcast"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Overlady Reads",
                 "mkQu8ZpXpiQ", "We made ALL the Chouta!"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "DyC75Axrq9U",
                 "A Certain Scadrian's Bones | JordanCon 2021 WoBs Part 2 | Rhythm of War Shardcast"),
                ("Lux", "Reckoners", "Reckoners", "Shardcast", "KzBwmWjITzk",
                 "Lux Reactions | Reckoners Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream",
                 "0jkFxl2ezC0", "Patron Q&A Stream!"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "ijI1uYtUxag",
                 "Kaladin | Rhythm of War Shardcast"),
                ("Sunreach", "Skyward", "Cytoverse", "Shardcast", "vISUKY_kOPI",
                 "Sunreach Minisode | Skyward | Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Shardcast", "yA68pEkOy7k",
                 "Cosmere Beefs 2: Beef Stew | Shardcast"),
                ("Multiple", "Multiple", "Cosmere", "Challenge", "8WcmRAKGvUc",
                 "Guess the Sanderson Challenge, Part 2!"),
                ("Multiple", "Multiple", "Multiple", "Shardcast", "737DCuJARfI",
                 "Brandon Sanderson's Use of Horror | Shardcast"),
                ("ReDawn", "Skyward", "Cytoverse", "Shardcast", "pR74icyGD8Q",
                 "ReDawn Reactions \"Mini\"sode | Skyward Shardcast"),
                ("Multiple", "Mistborn", "Cosmere", "Shardcast", "uMAX-ymwTBY",
                 "Medallions & Magitech of Southern Scadrial | Mistborn Shardcast"),
                ("Multiple", "Multiple", "Multiple", "Live Stream", "cZ9uP3bqBsE",
                 "17th Shard November Chatting Stream"),
                ("Multiple", "Stormlight Archive", "Cosmere", "Shardcast", "k9liwCPZZ9E",
                 "Jasnah | Rhythm of War Shardcast"),
                ("Cytonic", "Skyward", "Cytoverse", "Solo Review", "leggchPjUMk",
                 "Cytonic Spoiler-Free Review: This One Will Be Divisive!"),
                ("Cytonic", "Skyward", "Cytoverse", "Shardcast", "_981G7bZeho", "Cytonic Reactions | Shardcast")]
