# Name, handle
person_data = [("Kerry", "KChan"),
               ("Ian", "WeiryWriter"),
               ("David", "Windrunner"),
               ("Eric", "Chaos"),
               ("Alyx", "FeatherWriter"),
               ("Ben", "Overlord Jebus"),
               ("Matt", "Comatose"),
               ("Shannon", "Greywatch"),
               ("Ewan Johnson", ""),  # Special guest: Arcturus XR
               ("Evgeni", "Argent"),
               ("Rosemary", "Kaymyth"),
               ("Grace", "thegatorgirl"),
               ("Josh", "Rubix"),
               ("Joshua", "jofwu"),
               ("Mi'chelle", "firstRainbowRose"),
               ("Colton", "coltonx9"),
               ("Marvin", "Paleo"),
               ("Danielle", "FelCandy"),
               ("Lucy", "Empress"),
               ("Isaac Stewart", ""),
               ("Kara Stewart", ""),
               ("Daniel Greene", ""),
               ("Brandon Sanderson", ""),
               ("Jessie", "LadyLameness"),
               ("Kadie", "AonEne"),
               ("Ala", "Rasarr"),
               ("Merphy Napier", ""),
               ("Payden", "OttoDidact"),
               ("Veronica", "Cheyanne Sedai"),
               ("Mestiv", "Mestiv")]
